### ISSUE TITLE
Line break detection errors

### ISSUE THREAD

**Issue by stresslimit** [sorich87/import-users-from-csv#4]
When formatting .csv files in excel on a mac, the plugin doesn't work, but doesn't log an error. I finally figured out what the problem was, and solved by a manual treatment in vi in the terminal.

I did all your treatments and data formatting on the list, saved in excel and closed, then opened with vi in terminal and run the
following:

:%s/\r/\r/g

This will replace line break errors with proper line breaks.

**Comment by sorich87** [comment]
I don't use Excel on my Mac, unfortunately. But there were people who used it successfully in the past. Maybe the bug was introduced by a recent change.

Please can you explain what ":%s/\r/\r/g" does?
As far as I know, it replaces lines endings \r by lines endings \r, and that wouldn't do anything. But I maybe wrong.
Or did you want to write ":%s/\r/\r\n/g"? or something else?

**Comment by sorich87** [comment]
It looks like it works when you choose "Windows Comma Separated (.csv)" as CSV format.

See http://wordpress.org/support/topic/plugin-import-users-from-csv-no-user-was-successfully-imported#post-2796211.

I am closing the issue then. Please reopen if you have more information.
